---
- name: Test ftp configuration
  hosts: localhost
  tasks:
  - name: Install lftp
    yum:
      name: lftp
      state: latest
  - name: Upload file using lftp
    shell: >
      lftp 172.31.15.94 <<EOF
      cd pub
      put /etc/hosts
      EOF
...
