---
- name: generate SSH key
  hosts: localhost
  vars:
    ssh_key_filename: id_rsa
  vars_files:
    - vars/users
  tasks:
    - name: Create user directories
      file:
        dest: "files/{{ item.username }}"
        state: directory
      loop: "{{ users }}"
    - name: generate SSH key "{{ssh_key_filename}}"
      openssh_keypair:
        path: "{{ 'files/' + item.username + '/' + ssh_key_filename }}"
        type: rsa
        size: 4096
        state: present
        force: no
      loop: "{{ users }}"
...
